/*
try catch block

try{
    some codes of the code....
}catch (error) {
    console.log(error)
}
*/ 


// const username = "Akash";
// console.log(myname);
// console.log(username); // it will occur an error bcox our first line has'nt executed hence it did'nt goes to the second line.



// trying with catch block 

const username = "Akash";
try{
    console.log(myname);
} catch(error){
    console.log("error Occured");
}
console.log(username);